# Generated by Django 3.2.4 on 2021-06-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('text', models.CharField(max_length=100, verbose_name='Текст')),
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('text', models.CharField(max_length=100, verbose_name='Text')),
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
